### PR TITLE
DEVOPS-1658: Set `JENKINS_RUN` to jenkins-local

### PR DESCRIPTION
**Pull request by mwarkentin**

### CODE REVIEW

**Comment by mwarkentin** [comment]
https://github.com/waveaccounting/cde-provisioning/pull/149

**Comment by jfilipe** [comment]
@mwarkentin hey dude! hope all is well. you probably want to make this repo private. i was getting notifications for all this.

**Comment by mwarkentin** [comment]
@jfilipe @zuzelvp and anyone else getting notifications from this - sorry! It's a fork of a public repo, so we can't make it private. It's likely you were automatically added as a watcher when we forked it, so you can remove yourself by clicking the "Unwatch" button at the top of the repo.

Sorry again!

**Comment by zuzelvp** [comment]
No problem

**Comment by jfilipe** [comment]
There is a way of forking a public repo and making it private. We have done it a bunch at theScore. Checkout http://stackoverflow.com/a/28191261

Anyhow, no worries!

**Pull request closed without merging**
